server:
  port: 8083
  servlet:
   context-path: /employee
   
spring:
  security:
    user:
      name: employee
      password: M4ster99
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://discovery:M4ster99@localhost:8081/eureka}
  instance:
    preferIpAddress: true