management.endpoint.prometheus.enabled=true
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.tracing.sampling.probability=1

application.rest.baseUrl=http://localhost:61003

spring.cache.type=redis
spring.cache.port.redis.time-to-live=60000

spring.data.redis.host=redis-16194.c305.ap-south-1-1.ec2.redns.redis-cloud.com
spring.data.redis.port=16194
spring.data.redis.username=${application.redis.username}
spring.data.redis.password=${application.redis.password}