server:
  port: 8082
  servlet:
   context-path: /aggregate
spring:
  security:
    user:
      name: aggregate
      password: M4ster99
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://discovery:M4ster99@localhost:8081/eureka}
  instance:
    preferIpAddress: true
microservices:
    employee-service:
       url: http://EMPLOYEE-SERVICE/employee/id
       username: employee
       password: M4ster99
    vaccination-service:
       url: http://VACCINATION-SERVICE/vaccination/id
       username: vaccination
       password: M4ster99
feign:
 hystrix:
   enabled: true
 circuitbreaker:
   enabled: true